# Generated by Django 3.2.8 on 2023-09-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suit2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suitability',
            name='cardNumber',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='suitability',
            name='channel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='suitability',
            name='createBy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='suitability',
            name='createDT',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='suitability',
            name='docVersion',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='suitability',
            name='evaluateDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suitability',
            name='jsonData',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suitability',
            name='score',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='suitability',
            name='status',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='suitability',
            name='suitLevel',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='suitability',
            name='updateBy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='suitability',
            name='updateDT',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suitability',
            name='compCode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
