# Generated by Django 3.2.8 on 2023-09-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suit2', '0002_auto_20230912_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suitability',
            name='cardNumber',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='suitability',
            name='compCode',
            field=models.CharField(max_length=50),
        ),
    ]
