# Generated by Django 3.2.8 on 2023-09-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suit2', '0003_auto_20230912_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suitability',
            name='updateDT',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
