# Generated by Django 3.2.8 on 2023-09-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suit2', '0004_alter_suitability_updatedt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suitability',
            name='updateDT',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
