# Generated by Django 3.2.8 on 2023-09-14 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mitmaster', '0013_auto_20220629_1557'),
        ('suit2', '0005_alter_suitability_updatedt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suitability',
            name='cardNumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suitability', to='mitmaster.mit_client'),
        ),
    ]
