# Generated by Django 3.2.8 on 2023-09-14 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suit2', '0006_alter_suitability_cardnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suitability',
            old_name='cardNumber',
            new_name='custCode',
        ),
    ]
