# Generated by Django 3.2.8 on 2023-09-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suit2', '0007_rename_cardnumber_suitability_custcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suitability',
            name='custCode',
        ),
        migrations.AddField(
            model_name='suitability',
            name='cardNumber',
            field=models.CharField(default=0, max_length=13),
            preserve_default=False,
        ),
    ]
