# Generated by Django 3.2.8 on 2023-10-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suit2', '0008_auto_20230915_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='suitability',
            name='custType',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
