# FROM python:3.10-alpine
FROM python:3.10.14-alpine

ENV PYTHONUNBUFFERED 1

# RUN mkdir -p /vol/web/media
RUN mkdir -p /vol/web/static
# RUN adduser -D user
# RUN chown -R user:user /vol
# RUN chmod -R 755 /vol/web
# USER user

WORKDIR /django
COPY ./mitapi/requirements.txt requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
COPY . .

RUN python ./mitapi/manage.py collectstatic --noinput --clear
