# Generated by Django 3.2.8 on 2022-01-17 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mit_cmp_consentmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compCode', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('consStatus', models.CharField(max_length=1)),
                ('custCategory', models.CharField(max_length=10)),
                ('requestData', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=500)),
                ('effectFromDate', models.DateField()),
                ('effectToDate', models.DateField()),
                ('publishDate', models.DateField()),
                ('createDate', models.DateField()),
                ('updateDate', models.DateField()),
                ('createBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mit_cmp_consentmas_created', to=settings.AUTH_USER_MODEL)),
                ('updateBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mit_cmp_consentmas_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
