# Generated by Django 3.2.8 on 2022-01-17 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmpapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mit_cmp_consentmas',
            name='createBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mit_cmp_consentmas_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mit_cmp_consentmas',
            name='updateBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mit_cmp_consentmas_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
