# Generated by Django 3.2.8 on 2022-01-17 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmpapi', '0002_auto_20220117_0423'),
    ]

    operations = [
        migrations.CreateModel(
            name='mit_cmp_Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compCode', models.CharField(max_length=50)),
                ('custCode', models.CharField(max_length=50)),
                ('respMethod', models.CharField(max_length=10)),
                ('respStatus', models.CharField(max_length=50)),
                ('respDate', models.DateField()),
                ('reasonNotAgree', models.TextField(max_length=500)),
                ('respReference', models.CharField(max_length=1000)),
                ('createDate', models.DateField()),
                ('updateDate', models.DateField()),
                ('consent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmpapi.mit_cmp_consentmas')),
                ('createBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mit_cmp_response_created', to=settings.AUTH_USER_MODEL)),
                ('custRef', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mit_cmp_response_custRef', to=settings.AUTH_USER_MODEL)),
                ('updateBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mit_cmp_response_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'index_together': {('consent', 'custCode', 'custRef')},
            },
        ),
    ]
