# Generated by Django 3.2.8 on 2022-01-17 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmpapi', '0003_mit_cmp_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mit_cmp_consentmas',
            name='consStatus',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='mit_cmp_consentmas',
            name='custCategory',
            field=models.CharField(choices=[('ALL', 'All'), ('INT', 'For Internal'), ('CUST', 'For Customer'), ('LBDU', 'For LBDU'), ('BOND', 'For BOND'), ('PRIVATE', 'For Private Fund')], default='ALL', max_length=10),
        ),
        migrations.AlterField(
            model_name='mit_cmp_consentmas',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_consentmas',
            name='effectFromDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_consentmas',
            name='effectToDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_consentmas',
            name='publishDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_consentmas',
            name='requestData',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_response',
            name='custCode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_response',
            name='custRef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mit_cmp_response_custRef', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mit_cmp_response',
            name='respMethod',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_response',
            name='respStatus',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
