# Generated by Django 3.2.8 on 2022-01-17 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0004_auto_20220117_0501'),
    ]

    operations = [
        migrations.CreateModel(
            name='mit_master_value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compCode', models.CharField(max_length=50)),
                ('refType', models.CharField(max_length=50)),
                ('refCode', models.CharField(max_length=50)),
                ('nameTh', models.CharField(max_length=200)),
                ('nameEn', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=1)),
                ('seq', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='mit_cmp_consentmas',
            name='consStatus',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='mit_cmp_consentmas',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_consentmas',
            name='custCategory',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mit_cmp_consentmas',
            name='updateDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_response',
            name='createBy',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mit_cmp_response',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_response',
            name='updateBy',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mit_cmp_response',
            name='updateDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='mit_cmp_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compCode', models.CharField(max_length=50)),
                ('reqCategory', models.CharField(max_length=3)),
                ('reqDesc', models.TextField(max_length=300)),
                ('workFlowProcess_Ref', models.CharField(max_length=100)),
                ('approveStatus', models.CharField(max_length=20)),
                ('approveDate', models.DateField()),
                ('resonForReject', models.TextField(max_length=300)),
                ('approveDesc', models.TextField(max_length=300)),
                ('finishBy', models.CharField(max_length=50)),
                ('finishDate', models.DateField()),
                ('finishDesc', models.TextField(max_length=300)),
                ('createBy', models.CharField(max_length=50)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('updateBy', models.CharField(max_length=50)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('consent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmpapi.mit_cmp_consentmas')),
            ],
            options={
                'index_together': {('consent',)},
            },
        ),
    ]
