# Generated by Django 3.2.8 on 2022-01-17 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmpapi', '0005_auto_20220117_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='mit_cmp_request',
            name='custCode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mit_cmp_request',
            name='custRef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mit_cmp_request_custRef', to=settings.AUTH_USER_MODEL),
        ),
    ]
