# Generated by Django 3.2.8 on 2022-01-17 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmpapi', '0006_auto_20220117_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mit_cmp_consentmas',
            name='consStatus',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_consentmas',
            name='createBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mit_cmp_consentmas_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mit_cmp_consentmas',
            name='custCategory',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_consentmas',
            name='updateBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mit_cmp_consentmas_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
