# Generated by Django 3.2.8 on 2022-01-17 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0007_auto_20220117_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mit_cmp_request',
            name='finishDesc',
        ),
    ]
