# Generated by Django 3.2.8 on 2022-01-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0008_remove_mit_cmp_request_finishdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mit_cmp_response',
            name='createBy',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_response',
            name='reasonNotAgree',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_response',
            name='respDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_response',
            name='respReference',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_response',
            name='updateBy',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
