# Generated by Django 3.2.8 on 2022-01-18 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0009_auto_20220118_1009'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='mit_cmp_response',
            index_together={('consent', 'custCode')},
        ),
        migrations.RemoveField(
            model_name='mit_cmp_response',
            name='custRef',
        ),
    ]
