# Generated by Django 3.2.8 on 2022-01-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0010_auto_20220118_1019'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mit_cmp_response',
            unique_together={('consent', 'custCode', 'respStatus')},
        ),
    ]
