# Generated by Django 3.2.8 on 2022-01-18 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0011_alter_mit_cmp_response_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mit_cmp_response',
            unique_together={('consent', 'custCode')},
        ),
    ]
