# Generated by Django 3.2.8 on 2022-01-19 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0012_alter_mit_cmp_response_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mit_cmp_request',
            name='custRef',
        ),
    ]
