# Generated by Django 3.2.8 on 2022-01-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0013_remove_mit_cmp_request_custref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mit_cmp_request',
            name='approveDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_request',
            name='approveDesc',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_request',
            name='approveStatus',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_request',
            name='createBy',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_request',
            name='finishBy',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_request',
            name='finishDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_request',
            name='reqDesc',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_request',
            name='resonForReject',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_request',
            name='updateBy',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_request',
            name='workFlowProcess_Ref',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
