# Generated by Django 3.2.8 on 2022-01-26 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0014_auto_20220119_0341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mit_cmp_request',
            name='reqDesc',
        ),
        migrations.AddField(
            model_name='mit_cmp_request',
            name='reqDetail',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='mit_cmp_request',
            name='reqReason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='mit_cmp_requestCFG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compCode', models.CharField(max_length=50)),
                ('reqCategory', models.CharField(max_length=3)),
                ('reqTopic', models.CharField(max_length=100)),
                ('reqDescription', models.CharField(max_length=300)),
                ('consent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmpapi.mit_cmp_consentmas')),
            ],
        ),
    ]
