# Generated by Django 3.2.8 on 2022-01-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0015_auto_20220126_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='mit_cmp_requestcfg',
            name='showReqDetail',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='mit_cmp_requestcfg',
            name='showReqReason',
            field=models.BooleanField(null=True),
        ),
    ]
