# Generated by Django 3.2.8 on 2022-01-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0016_auto_20220126_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mit_cmp_request',
            old_name='reqReason',
            new_name='reqReasonChoice',
        ),
        migrations.AddField(
            model_name='mit_cmp_request',
            name='reqReasonText',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
