# Generated by Django 3.2.8 on 2022-01-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0017_auto_20220127_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mit_cmp_request',
            name='reqCategory',
        ),
        migrations.RemoveField(
            model_name='mit_cmp_requestcfg',
            name='reqCategory',
        ),
        migrations.AddField(
            model_name='mit_cmp_request',
            name='reqCode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mit_cmp_requestcfg',
            name='reqCode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
