# Generated by Django 3.2.8 on 2022-01-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0018_auto_20220127_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mit_cmp_request',
            name='approveDesc',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_request',
            name='reqDetail',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_request',
            name='reqReasonText',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_request',
            name='resonForReject',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_requestcfg',
            name='reqDescription',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mit_master_value',
            name='nameEn',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mit_master_value',
            name='nameTh',
            field=models.CharField(max_length=500),
        ),
    ]
