# Generated by Django 3.2.8 on 2022-01-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0019_auto_20220127_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='mit_cmp_requestcfg',
            name='reqResonChoice',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
