# Generated by Django 3.2.8 on 2022-01-27 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0020_mit_cmp_requestcfg_reqresonchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mit_cmp_requestcfg',
            name='consent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjectRights', to='cmpapi.mit_cmp_consentmas'),
        ),
    ]
