# Generated by Django 3.2.8 on 2022-01-31 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmpapi', '0021_alter_mit_cmp_requestcfg_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mit_cmp_consentmas',
            name='consStatus',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_consentmas',
            name='createBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mit_cmp_consentmas_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mit_cmp_consentmas',
            name='custCategory',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_consentmas',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_consentmas',
            name='effectFromDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_consentmas',
            name='effectToDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_consentmas',
            name='publishDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_consentmas',
            name='requestData',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_consentmas',
            name='updateBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mit_cmp_consentmas_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mit_cmp_response',
            name='createBy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_response',
            name='custCode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_response',
            name='reasonNotAgree',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_response',
            name='respDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_response',
            name='respMethod',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_response',
            name='respReference',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_response',
            name='respStatus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_response',
            name='updateBy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
