# Generated by Django 3.2.8 on 2022-01-31 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mitmaster', '0003_auto_20220131_0428'),
        ('cmpapi', '0024_alter_mit_cmp_response_custcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mit_cmp_response',
            name='custCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mitmaster.mit_client'),
        ),
    ]
