# Generated by Django 3.2.8 on 2022-01-31 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0025_alter_mit_cmp_response_custcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mit_cmp_response',
            name='custCode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
