# Generated by Django 3.2.8 on 2022-01-31 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0027_alter_mit_cmp_response_custcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mit_master_value',
        ),
    ]
