# Generated by Django 3.2.8 on 2022-01-31 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mitmaster', '0003_auto_20220131_0428'),
        ('cmpapi', '0028_delete_mit_master_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mit_cmp_response',
            name='consent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentRef', to='cmpapi.mit_cmp_consentmas'),
        ),
        migrations.AlterField(
            model_name='mit_cmp_response',
            name='custCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custCodeRef', to='mitmaster.mit_client'),
        ),
        migrations.AlterUniqueTogether(
            name='mit_cmp_response',
            unique_together=set(),
        ),
    ]
