# Generated by Django 3.2.8 on 2022-01-31 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mitmaster', '0003_auto_20220131_0428'),
        ('cmpapi', '0030_auto_20220131_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mit_cmp_response',
            name='consent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmpapi.mit_cmp_consentmas'),
        ),
        migrations.AlterField(
            model_name='mit_cmp_response',
            name='custCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mitmaster.mit_client'),
        ),
    ]
