# Generated by Django 3.2.8 on 2022-01-31 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0031_auto_20220131_1007'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='mit_cmp_response',
            index_together=set(),
        ),
    ]
