# Generated by Django 3.2.8 on 2022-01-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitmaster', '0003_auto_20220131_0428'),
        ('cmpapi', '0032_alter_mit_cmp_response_index_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mit_cmp_response',
            name='consent',
        ),
        migrations.AddField(
            model_name='mit_cmp_response',
            name='consent',
            field=models.ManyToManyField(to='cmpapi.mit_cmp_consentmas'),
        ),
        migrations.RemoveField(
            model_name='mit_cmp_response',
            name='custCode',
        ),
        migrations.AddField(
            model_name='mit_cmp_response',
            name='custCode',
            field=models.ManyToManyField(to='mitmaster.mit_client'),
        ),
    ]
