# Generated by Django 3.2.8 on 2022-02-01 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mitmaster', '0003_auto_20220131_0428'),
        ('cmpapi', '0033_auto_20220131_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mit_cmp_response',
            name='consent',
        ),
        migrations.AddField(
            model_name='mit_cmp_response',
            name='consent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmpapi.mit_cmp_consentmas'),
        ),
        migrations.RemoveField(
            model_name='mit_cmp_response',
            name='custCode',
        ),
        migrations.AddField(
            model_name='mit_cmp_response',
            name='custCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mitmaster.mit_client'),
        ),
    ]
