# Generated by Django 3.2.8 on 2022-02-07 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0034_auto_20220201_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mit_cmp_response',
            name='consent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consentResponse', to='cmpapi.mit_cmp_consentmas'),
        ),
    ]
