# Generated by Django 3.2.8 on 2022-02-07 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mitmaster', '0004_alter_mit_client_options'),
        ('cmpapi', '0035_alter_mit_cmp_response_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mit_cmp_response',
            name='consent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consentMaster', to='cmpapi.mit_cmp_consentmas'),
        ),
        migrations.AlterField(
            model_name='mit_cmp_response',
            name='custCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consentResponse', to='mitmaster.mit_client'),
        ),
    ]
