# Generated by Django 3.2.8 on 2022-02-07 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mitmaster', '0004_alter_mit_client_options'),
        ('cmpapi', '0036_auto_20220207_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mit_cmp_request',
            name='custCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientRequest', to='mitmaster.mit_client'),
        ),
    ]
