# Generated by Django 3.2.8 on 2022-02-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0037_alter_mit_cmp_request_custcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mit_cmp_request',
            name='approveDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_request',
            name='approveDesc',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_request',
            name='approveStatus',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mit_cmp_request',
            name='finishBy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_request',
            name='finishDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_request',
            name='reqCode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mit_cmp_request',
            name='reqDetail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_request',
            name='reqReasonChoice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_request',
            name='reqReasonText',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_request',
            name='resonForReject',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_request',
            name='updateBy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_request',
            name='workFlowProcess_Ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_requestcfg',
            name='reqCode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mit_cmp_requestcfg',
            name='reqResonChoice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_requestcfg',
            name='showReqDetail',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_requestcfg',
            name='showReqReason',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
