# Generated by Django 3.2.8 on 2022-03-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0038_auto_20220208_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mit_cmp_response',
            name='respDate',
        ),
        migrations.AlterField(
            model_name='mit_cmp_response',
            name='respStatus',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
