# Generated by Django 3.2.8 on 2022-03-27 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0039_auto_20220327_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mit_cmp_request',
            name='consent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmpapi.mit_cmp_consentmas'),
        ),
    ]
