# Generated by Django 3.2.8 on 2022-03-27 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0040_alter_mit_cmp_request_consent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mit_cmp_request',
            old_name='finishBy',
            new_name='reqStatus',
        ),
        migrations.RemoveField(
            model_name='mit_cmp_request',
            name='approveDate',
        ),
        migrations.RemoveField(
            model_name='mit_cmp_request',
            name='approveDesc',
        ),
        migrations.RemoveField(
            model_name='mit_cmp_request',
            name='approveStatus',
        ),
        migrations.RemoveField(
            model_name='mit_cmp_request',
            name='finishDate',
        ),
        migrations.RemoveField(
            model_name='mit_cmp_request',
            name='resonForReject',
        ),
    ]
