# Generated by Django 3.2.8 on 2022-03-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0041_auto_20220327_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mit_cmp_request',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
