# Generated by Django 3.2.8 on 2022-03-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0042_alter_mit_cmp_request_createdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mit_cmp_request',
            name='createBy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_request',
            name='updateDate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
