# Generated by Django 3.2.8 on 2022-04-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0043_auto_20220327_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='mit_cmp_consentmas',
            name='canChange',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='mit_cmp_consentmas',
            name='defaultValue',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mit_cmp_request',
            name='reqAccount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
