# Generated by Django 3.2.8 on 2022-04-07 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0044_auto_20220406_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mit_cmp_consentmas',
            old_name='canChange',
            new_name='canChanges',
        ),
        migrations.RenameField(
            model_name='mit_cmp_consentmas',
            old_name='defaultValue',
            new_name='defaultValues',
        ),
        migrations.RenameField(
            model_name='mit_cmp_request',
            old_name='reqAccount',
            new_name='reqAccounts',
        ),
    ]
