# Generated by Django 3.2.8 on 2022-04-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0045_auto_20220407_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='mit_cmp_consentmas',
            name='seq',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
