# Generated by Django 3.2.8 on 2022-04-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0046_mit_cmp_consentmas_seq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mit_cmp_consentmas',
            name='consStatus',
            field=models.CharField(blank=True, choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1, null=True),
        ),
    ]
