# Generated by Django 3.2.8 on 2022-05-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0047_alter_mit_cmp_consentmas_consstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='mit_cmp_request',
            name='reqRef',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
