# Generated by Django 3.2.8 on 2022-05-11 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('mitmaster', '0009_mit_client_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmpapi', '0048_mit_cmp_request_reqref'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historicalmit_cmp_Response',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('compCode', models.CharField(max_length=50)),
                ('respMethod', models.CharField(blank=True, max_length=10, null=True)),
                ('respStatus', models.CharField(blank=True, max_length=1, null=True)),
                ('reasonNotAgree', models.TextField(blank=True, max_length=500, null=True)),
                ('respReference', models.CharField(blank=True, max_length=1000, null=True)),
                ('createBy', models.CharField(blank=True, max_length=50, null=True)),
                ('createDate', models.DateTimeField(blank=True, editable=False)),
                ('updateBy', models.CharField(blank=True, max_length=50, null=True)),
                ('updateDate', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('consent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cmpapi.mit_cmp_consentmas')),
                ('custCode', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mitmaster.mit_client')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical mit_cmp_ response',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalmit_cmp_request',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('compCode', models.CharField(max_length=50)),
                ('reqRef', models.CharField(blank=True, max_length=50, null=True)),
                ('reqCode', models.CharField(max_length=50)),
                ('reqDetail', models.CharField(blank=True, max_length=500, null=True)),
                ('reqReasonText', models.CharField(blank=True, max_length=500, null=True)),
                ('reqReasonChoice', models.CharField(blank=True, max_length=100, null=True)),
                ('workFlowProcess_Ref', models.CharField(blank=True, max_length=100, null=True)),
                ('reqStatus', models.CharField(blank=True, max_length=50, null=True)),
                ('reqAccounts', models.CharField(blank=True, max_length=100, null=True)),
                ('createBy', models.CharField(blank=True, max_length=50, null=True)),
                ('createDate', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updateBy', models.CharField(blank=True, max_length=50, null=True)),
                ('updateDate', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('consent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cmpapi.mit_cmp_consentmas')),
                ('custCode', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mitmaster.mit_client')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical mit_cmp_request',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
