# Generated by Django 3.2.8 on 2022-05-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0049_historicalmit_cmp_request_historicalmit_cmp_response'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmit_cmp_request',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical mit_cmp_request', 'verbose_name_plural': 'historical mit_cmp_requests'},
        ),
        migrations.AlterModelOptions(
            name='historicalmit_cmp_response',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical mit_cmp_ response', 'verbose_name_plural': 'historical mit_cmp_ responses'},
        ),
        migrations.AddField(
            model_name='historicalmit_cmp_request',
            name='respDescription',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mit_cmp_request',
            name='respDescription',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmit_cmp_request',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmit_cmp_response',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
