# Generated by Django 3.2.8 on 2022-06-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0050_auto_20220525_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmit_cmp_response',
            name='reasonNotAgree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_response',
            name='reasonNotAgree',
            field=models.TextField(blank=True, null=True),
        ),
    ]
