# Generated by Django 3.2.8 on 2022-06-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0051_auto_20220622_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmit_cmp_request',
            name='reqChannel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mit_cmp_request',
            name='reqChannel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
