# Generated by Django 3.2.8 on 2022-07-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0053_auto_20220629_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='mit_cmp_consentmas',
            name='crossCompFollow',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='mit_cmp_consentmas',
            name='crossCompTriger',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
