# Generated by Django 3.2.8 on 2022-07-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0054_auto_20220706_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmit_cmp_request',
            name='respMailText',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mit_cmp_request',
            name='respMailText',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
