# Generated by Django 3.2.8 on 2022-08-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0055_auto_20220714_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmit_cmp_request',
            name='reqDetail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmit_cmp_request',
            name='reqReasonText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmit_cmp_request',
            name='respDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmit_cmp_request',
            name='respMailText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_request',
            name='reqDetail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_request',
            name='reqReasonText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_request',
            name='respDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mit_cmp_request',
            name='respMailText',
            field=models.TextField(blank=True, null=True),
        ),
    ]
