# Generated by Django 3.2.8 on 2022-08-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0056_auto_20220801_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmit_cmp_request',
            name='requestDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalmit_cmp_response',
            name='requestDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mit_cmp_request',
            name='requestDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mit_cmp_response',
            name='requestDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
