# Generated by Django 3.2.8 on 2022-08-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0057_auto_20220808_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmit_cmp_request',
            name='consentCrossComp',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='historicalmit_cmp_response',
            name='consentCrossComp',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='mit_cmp_request',
            name='consentCrossComp',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='mit_cmp_response',
            name='consentCrossComp',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
