# Generated by Django 3.2.8 on 2023-09-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapi', '0058_auto_20220822_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mit_cmp_consentmas',
            name='seq',
            field=models.IntegerField(default=0),
        ),
    ]
