"""
Django settings for movierater project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-w097p2eb_c12ze_7kho2tfe!a6x7yb^8u1q4e2cy8tp+(-ncw1'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'changeme')

PROD = int(os.environ.get("PROD", default=0))

SEND_SMS = int(os.environ.get("SEND_SMS", default=0))

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
# DEBUG = bool(int(os.environ.get('DEBUG', 0)))


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(int(os.environ.get("DJANGO_DEBUG", 0)))

ALLOWED_HOSTS = [] if DEBUG else os.environ.get("DJANGO_ALLOWED_HOSTS").split(',')
print(" *** DEBUG:",DEBUG)
print(" *** ALLOWED_HOSTS:", ALLOWED_HOSTS)

# Not Recommended for Production
# CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = str(os.environ.get("CORS_ALLOWED_ORIGINS")).split(',')
# CORS_ALLOWED_ORIGINS =['http://localhost:3000','https://cpt-dev.southeastasia.cloudapp.azure.com','http://cpt-dev.southeastasia.cloudapp.azure.com']

CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS
# CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS if DEBUG else os.environ.get("CSRF_TRUSTED_ORIGINS").split(',')
# CSRF_TRUSTED_ORIGINS = ['http://localhost:']
CSRF_TRUSTED_ORIGINS = [origin.replace("http://", "https://") for origin in CSRF_TRUSTED_ORIGINS]


print(f"*DEBUG: {DEBUG}")
print(f"*ALLOWED_HOSTS: {ALLOWED_HOSTS}")
print(f"*CORS_ALLOWED_ORIGINS: {CORS_ALLOWED_ORIGINS}")
print(f"*CSRF_TRUSTED_ORIGINS: {CSRF_TRUSTED_ORIGINS}")
# print(f"*CSRF_COOKIE_SAMESITE: {CSRF_COOKIE_SAMESITE}")
# print(f"*SESSION_COOKIE_SAMESITE: {SESSION_COOKIE_SAMESITE}")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    
    #MARZ add installations here
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'base',

    'django_filters',
    
    'import_export',
    'simple_history',
    'anymail',
    'api',
    'cmpapi',
    'mitmaster',
    'suit2'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

# ALLOWED_HOSTS = []
# ALLOWED_HOSTS = ['portal.merchantasset.co.th', 'cpt-dev.southeastasia.cloudapp.azure.com',
#                  'cpt.southeastasia.cloudapp.azure.com', 'cpt.merchant.co.th', '198.211.99.20', 'localhost', '127.0.0.1', '52.187.135.46', '13.76.156.230']
# ALLOWED_HOSTS = [] if DEBUG else os.environ.get("DJANGO_ALLOWED_HOSTS").split(',')

# convert to string and split by comma
# ALLOWED_HOSTS = str(os.environ.get("DJANGO_ALLOWED_HOSTS")).split(',')


# For CSRF cookie
# CSRF_COOKIE_SAMESITE = 'Lax' # or 'None' (requires HTTPS), 'Strict'

# For session cookie (if applicable)
# SESSION_COOKIE_SAMESITE = 'Lax' # or 'None' (requires HTTPS), 'Strict'



ROOT_URLCONF = 'movierater.urls'

TEMPLATE_DIR = os.path.join(BASE_DIR, 'templates')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        # 'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'movierater.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("SQL_DATABASE", BASE_DIR / "db.sqlite3"),
        "USER": os.environ.get("SQL_USER", "user"),
        "PASSWORD": os.environ.get("SQL_PASSWORD", "password"),
        "HOST": os.environ.get("SQL_HOST", "localhost"),
        "PORT": os.environ.get("SQL_PORT", "5432"),
    }
}

REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'base.authentication.CookiesJWTAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 200,
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Bangkok'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# STATIC_URL = '/static/static/' # Development
# STATIC_ROOT = '/vol/web/static'  # Directory where static files are collected

# MEDIA_URL = '/static/media/'
# MEDIA_ROOT = '/vol/web/media'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

COMP_CODE = os.environ.get("COMP_CODE")

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MPAM_API_URL = os.environ.get("MPAM_API_URL")
MPAM_API_TOKEN = os.environ.get("MPAM_API_TOKEN")
MPAM_SMSGW_URL = os.environ.get("MPAM_SMSGW_URL")
MPAM_SMSGW_TOKEN = os.environ.get("MPAM_SMSGW_TOKEN")


ENABLE_APP_MAIL_EXTERNAL = os.environ.get("ENABLE_APP_MAIL_EXTERNAL")
ENABLE_APP_SMS_EXTERNAL = os.environ.get("ENABLE_APP_SMS_EXTERNAL")
ENABLE_TAX_SMS_EXTERNAL = os.environ.get("ENABLE_TAX_SMS_EXTERNAL")
ENABLE_TAX_MAIL_EXTERNAL = os.environ.get("ENABLE_TAX_MAIL_EXTERNAL")

MAILGUN_SENDER_DOMAIN = "merchantasset.co.th" if(str(COMP_CODE).lower() == 'mpam') else "merchant.co.th"
ANYMAIL = {
    "MAILGUN_API_KEY": os.environ.get("MAILGUN_API_KEY"),
    "MAILGUN_SENDER_DOMAIN": MAILGUN_SENDER_DOMAIN,
    "MAILGUN_API_URL": "https://api.mailgun.net/v3"
}

EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"
DEFAULT_FROM_EMAIL = "wealthservice@merchantasset.co.th"
SERVER_EMAIL = "your-server@example.com"

# 365 SMTP
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_USE_SSL = False
# EMAIL_HOST = os.environ.get("EMAIL_HOST")
# EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
# EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
# EMAIL_PORT = os.environ.get("EMAIL_PORT")

AZURE_CONTAINER_CONNECTION_STRING= os.environ.get("AZURE_CONTAINER_CONNECTION_STRING")
AZURE_CONTAINER_NAME= os.environ.get("AZURE_CONTAINER_NAME")

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=90),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,

    "ALGORITHM": "HS256",
    "SIGNING_KEY": os.environ.get('DJANGO_SECRET_KEY', 'changeme'),
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),

    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",
}