# Generated by Django 3.2.8 on 2022-01-31 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mit_master_value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compCode', models.CharField(max_length=50)),
                ('refType', models.CharField(max_length=50)),
                ('refCode', models.CharField(max_length=50)),
                ('nameTh', models.CharField(max_length=500)),
                ('nameEn', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=1)),
                ('seq', models.CharField(max_length=50)),
            ],
            options={
                'index_together': {('compCode', 'refType', 'refCode')},
            },
        ),
        migrations.CreateModel(
            name='mit_client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compCode', models.CharField(max_length=50)),
                ('cardNumber', models.CharField(max_length=13)),
                ('identificationCardType', models.CharField(max_length=15)),
                ('passportCountry', models.CharField(max_length=2, null=True)),
                ('cardExpiryDate', models.DateField(null=True)),
                ('title', models.CharField(max_length=5)),
                ('titleOther', models.CharField(max_length=50, null=True)),
                ('enFirstName', models.CharField(max_length=100)),
                ('enLastName', models.CharField(max_length=100)),
                ('thFirstName', models.CharField(max_length=100)),
                ('thLastName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('compCode', 'cardNumber')},
                'index_together': {('compCode', 'cardNumber')},
            },
        ),
    ]
