# Generated by Django 3.2.8 on 2022-01-31 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitmaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mit_client',
            name='cardExpiryDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mit_client',
            name='passportCountry',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mit_client',
            name='titleOther',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
