# Generated by Django 3.2.8 on 2022-01-31 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitmaster', '0002_auto_20220131_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mit_client',
            name='thFirstName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mit_client',
            name='thLastName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mit_client',
            name='title',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
