# Generated by Django 3.2.8 on 2022-02-07 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitmaster', '0003_auto_20220131_0428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mit_client',
            options={'ordering': ['thFirstName', 'thLastName']},
        ),
    ]
