# Generated by Django 3.2.8 on 2022-03-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitmaster', '0004_alter_mit_client_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mit_client',
            name='otpCounter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mit_client',
            name='otpIsVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mit_client',
            name='otpIsVerifiedDT',
            field=models.DateTimeField(null=True),
        ),
    ]
