# Generated by Django 3.2.8 on 2022-03-19 03:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mitmaster', '0005_auto_20220314_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='mit_client',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name=' Generation time '),
            preserve_default=False,
        ),
    ]
