# Generated by Django 3.2.8 on 2022-03-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitmaster', '0006_mit_client_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mit_client',
            name='otpCode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='mit_client',
            name='otpExpire',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mit_client',
            name='otpMethod',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mit_client',
            name='otpRef',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
