# Generated by Django 3.2.8 on 2022-03-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitmaster', '0007_auto_20220321_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mit_client',
            name='otpExpire',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mit_client',
            name='otpIsVerifiedDT',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
