# Generated by Django 3.2.8 on 2022-03-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitmaster', '0008_auto_20220321_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='mit_client',
            name='products',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
