# Generated by Django 3.2.8 on 2022-06-02 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mitmaster', '0009_mit_client_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historicalmit_client',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('compCode', models.CharField(max_length=50)),
                ('cardNumber', models.CharField(max_length=13)),
                ('identificationCardType', models.CharField(max_length=15)),
                ('passportCountry', models.CharField(blank=True, max_length=2, null=True)),
                ('cardExpiryDate', models.DateField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=5, null=True)),
                ('titleOther', models.CharField(blank=True, max_length=50, null=True)),
                ('enFirstName', models.CharField(max_length=100)),
                ('enLastName', models.CharField(max_length=100)),
                ('thFirstName', models.CharField(blank=True, max_length=100, null=True)),
                ('thLastName', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('products', models.CharField(blank=True, max_length=50, null=True)),
                ('otpMethod', models.CharField(blank=True, max_length=100, null=True)),
                ('otpIsVerified', models.BooleanField(default=False)),
                ('otpIsVerifiedDT', models.DateTimeField(blank=True, null=True)),
                ('otpCounter', models.IntegerField(default=0)),
                ('otpExpire', models.DateTimeField(blank=True, null=True)),
                ('otpRef', models.CharField(blank=True, max_length=6, null=True)),
                ('otpCode', models.CharField(blank=True, max_length=6, null=True)),
                ('add_time', models.DateTimeField(blank=True, editable=False, verbose_name=' Generation time ')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical mit_client',
                'verbose_name_plural': 'historical mit_clients',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
