# Generated by Django 3.2.8 on 2022-06-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitmaster', '0010_historicalmit_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmit_client',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mit_client',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
