# Generated by Django 3.2.8 on 2022-06-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitmaster', '0011_auto_20220620_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmit_client',
            name='createBy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalmit_client',
            name='createDate',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalmit_client',
            name='updateBy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalmit_client',
            name='updateDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mit_client',
            name='createBy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mit_client',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mit_client',
            name='updateBy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mit_client',
            name='updateDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
