# Generated by Django 3.2.8 on 2022-06-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitmaster', '0012_auto_20220621_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmit_client',
            name='channel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mit_client',
            name='channel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
