# Generated by Django 5.2.4 on 2025-07-14 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitmaster', '0013_auto_20220629_1557'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mit_client',
            new_name='mitmaster_m_compCod_25b32a_idx',
            old_fields=('compCode', 'cardNumber'),
        ),
        migrations.RenameIndex(
            model_name='mit_master_value',
            new_name='mitmaster_m_compCod_b84fc7_idx',
            old_fields=('compCode', 'refType', 'refCode'),
        ),
    ]
