# Generated by Django 5.2.4 on 2025-07-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitmaster', '0014_rename_mit_client_compCode_cardNumber_mitmaster_m_compcod_25b32a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmit_client',
            name='max_otp_try',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='historicalmit_client',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='historicalmit_client',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalmit_client',
            name='otp_max_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalmit_client',
            name='otp_ref',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='mit_client',
            name='max_otp_try',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='mit_client',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='mit_client',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mit_client',
            name='otp_max_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mit_client',
            name='otp_ref',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
