# Generated by Django 5.2.4 on 2025-07-14 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rating',
            new_name='api_rating_user_id_fe3be0_idx',
            old_fields=('user', 'movie'),
        ),
    ]
