def getCountryCode(input_value):

    countries = [
        { "code": "AD", "value": "ANDORRA", "description": "อันดอร์รา" },
        { "code": "AE", "value": "UNITED ARAB EMIRATES", "description": "สหรัฐอาหรับเอมิเรตส์" },
        { "code": "AF", "value": "AFGHANISTAN", "description": "อัฟกานิสถาน" },
        { "code": "AG", "value": "ANTIGUA AND BARBUDA", "description": "แอนติกาและบาร์บูดา" },
        { "code": "AI", "value": "ANGUILLA", "description": "แองกลิวลา" },
        { "code": "AL", "value": "ALBANIA", "description": "แอลเบเนีย" },
        { "code": "AM", "value": "ARMENIA", "description": "อาร์เมเนีย" },
        { "code": "AN", "value": "NETHERLANDS ANTILLES", "description": "เนเธอร์แลนด์แอนทิลลิส" },
        { "code": "AO", "value": "ANGOLA", "description": "แองโกลา" },
        { "code": "AQ", "value": "ANTARCTICA", "description": "แอนตาร์กติกา" },
        { "code": "AR", "value": "ARGENTINA", "description": "อาร์เจนตินา" },
        { "code": "AS", "value": "AMERICAN SAMOA", "description": "อเมริกันซามัว" },
        { "code": "AT", "value": "AUSTRIA", "description": "ออสเตรีย" },
        { "code": "AU", "value": "AUSTRALIA", "description": "ออสเตรเลีย" },
        { "code": "AW", "value": "ARUBA", "description": "อารูบา" },
        { "code": "AX", "value": "ALAND ISLANDS", "description": "หมู่เกาะอะแลนด์" },
        { "code": "AZ", "value": "AZERBAIJAN", "description": "อาเซอร์ไบจาน" },
        { "code": "BA", "value": "BOSNIA AND HERZEGOVINA", "description": "บอสเนียและเฮอร์เซโกวีนา" },
        { "code": "BB", "value": "BARBADOS", "description": "บาร์เบโดส" },
        { "code": "BD", "value": "BANGLADESH", "description": "บังกลาเทศ" },
        { "code": "BE", "value": "BELGIUM", "description": "เบลเยียม" },
        { "code": "BF", "value": "BURKINA FASO", "description": "บูร์กินาฟาโซ" },
        { "code": "BG", "value": "BULGARIA", "description": "บัลแกเรีย" },
        { "code": "BH", "value": "BAHRAIN", "description": "บาห์เรน" },
        { "code": "BI", "value": "BURUNDI", "description": "บุรุนดี" },
        { "code": "BJ", "value": "BENIN", "description": "เบนิน" },
        { "code": "BL", "value": "SAINT-BARTHELEMY", "description": "เซนต์บาร์เธเลมี" },
        { "code": "BM", "value": "BERMUDA", "description": "เบอร์มิวดา" },
        { "code": "BN", "value": "BRUNEI DARUSSALAM", "description": "บรูไนดารุสซาลาม" },
        { "code": "BO", "value": "BOLIVIA, PLURINATIONAL STATE OF", "description": "โบลิเวีย" },
        { "code": "BR", "value": "BRAZIL", "description": "บราซิล" },
        { "code": "BS", "value": "BAHAMAS", "description": "บาฮามาส" },
        { "code": "BT", "value": "BHUTAN", "description": "ภูฏาน" },
        { "code": "BV", "value": "BOUVET ISLAND", "description": "โบเวทไอแลนด์" },
        { "code": "BW", "value": "BOTSWANA", "description": "บอตสวานา" },
        { "code": "BY", "value": "BELARUS", "description": "เบลารุส" },
        { "code": "BZ", "value": "BELIZE", "description": "เบลีซ" },
        { "code": "CA", "value": "CANADA", "description": "แคนาดา" },
        { "code": "CC", "value": "COCOS (KEELING) ISLANDS", "description": "หมู่เกาะโคโคส, หมู่เกาะคีลิง" },
        { "code": "CD", "value": "CONGO (DEMOCRATIC REPUBLIC OF THE)", "description": "สาธารณรัฐประชาธิปไตยคองโก" },
        { "code": "CF", "value": "CENTRAL AFRICAN REPUBLIC", "description": "สาธารณรัฐแอฟริกากลาง" },
        { "code": "CG", "value": "CONGO", "description": "สาธารณรัฐคองโก" },
        { "code": "CH", "value": "SWITZERLAND", "description": "สวิตเซอร์แลนด์" },
        { "code": "CI", "value": "COTE D’ IVOIRE", "description": "โกตดิวัวร์" },
        { "code": "CK", "value": "COOK ISLANDS", "description": "หมู่เกาะคุก" },
        { "code": "CL", "value": "CHILE", "description": "ชิลี" },
        { "code": "CM", "value": "CAMEROON", "description": "แคเมอรูน" },
        { "code": "CN", "value": "CHINA", "description": "จีน" },
        { "code": "CO", "value": "COLOMBIA", "description": "โคลอมเบีย" },
        { "code": "CR", "value": "COSTA RICA", "description": "คอสตาริกา" },
        { "code": "CS", "value": "SERBIA AND MONTENEGRO", "description": "เซอร์เบียและมอนเตเนโกร" },
        { "code": "CU", "value": "CUBA", "description": "คิวบา" },
        { "code": "CV", "value": "CABO VERDE", "description": "กาบูเวร์ดี" },
        { "code": "CX", "value": "CHRISTMAS ISLAND", "description": "เกาะคริสต์มาส" },
        { "code": "CY", "value": "CYPRUS", "description": "ไซปรัส" },
        { "code": "CZ", "value": "CZECH REPUBLIC", "description": "สาธารณรัฐเช็ก" },
        { "code": "DD", "value": "EAST GERMANY", "description": "เยอรมันตะวันออก" },
        { "code": "DE", "value": "GERMANY", "description": "เยอรมนี" },
        { "code": "DJ", "value": "DJIBOUTI", "description": "จิบูตี" },
        { "code": "DK", "value": "DENMARK", "description": "เดนมาร์ก" },
        { "code": "DM", "value": "DOMINICA", "description": "โดมินิกา" },
        { "code": "DO", "value": "DOMINICAN REPUBLIC", "description": "สาธารณรัฐโดมินิกัน" },
        { "code": "DZ", "value": "ALGERIA", "description": "แอลจีเรีย" },
        { "code": "EC", "value": "ECUADOR", "description": "เอกวาดอร์" },
        { "code": "EE", "value": "ESTONIA", "description": "เอสโตเนีย" },
        { "code": "EG", "value": "EGYPT", "description": "อียิปต์" },
        { "code": "EH", "value": "WESTERN SAHARA", "description": "เวสเทิร์น ซาฮารา" },
        { "code": "ER", "value": "ERITREA", "description": "เอริเทรีย" },
        { "code": "ES", "value": "SPAIN", "description": "สเปน" },
        { "code": "ET", "value": "ETHIOPIA", "description": "เอธิโอเปีย" },
        { "code": "FI", "value": "FINLAND", "description": "ฟินแลนด์" },
        { "code": "FJ", "value": "FIJI", "description": "ฟิจิ" },
        { "code": "FK", "value": "FALKLAND ISLANDS(MALVINAS)", "description": "หมู่เกาะฟอล์กแลนด์" },
        { "code": "FM", "value": "MICRONESIA (FEDERATED STATES OF)", "description": "ไมโครนีเซีย" },
        { "code": "FO", "value": "FAEROE ISLANDS", "description": "หมู่เกาะแฟโร" },
        { "code": "FR", "value": "FRANCE", "description": "ฝรั่งเศส" },
        { "code": "GA", "value": "GABON", "description": "กาบอง" },
        { "code": "GB", "value": "UNITED KINGDOM", "description": "สหราชอาณาจักร" },
        { "code": "GD", "value": "GRENADA", "description": "เกรเนดา" },
        { "code": "GE", "value": "GEORGIA", "description": "จอร์เจีย" },
        { "code": "GF", "value": "FRENCH GUIANA", "description": "เฟรนช์เกียนา" },
        { "code": "GG", "value": "GUERNSEY,C.I.", "description": "เกาะเกอร์นซี" },
        { "code": "GH", "value": "GHANA", "description": "กานา" },
        { "code": "GI", "value": "GIBRALTAR", "description": "ยิบรอลตาร์" },
        { "code": "GL", "value": "GREENLAND", "description": "กรีนแลนด์, กะลาลลิตนูนาต" },
        { "code": "GM", "value": "GAMBIA", "description": "แกมเบีย" },
        { "code": "GN", "value": "GUINEA", "description": "กินี" },
        { "code": "GP", "value": "GUADELOUPE", "description": "กวาเดอลูป" },
        { "code": "GQ", "value": "EQUATORIAL GUINEA", "description": "อิเควทอเรียลกินี" },
        { "code": "GR", "value": "GREECE", "description": "กรีซ" },
        { "code": "GS", "value": "SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS", "description": "เกาะเซาท์ จอร์เจียและหมู่เกาะเซาท์แซนด์วิช" },
        { "code": "GT", "value": "GUATEMALA", "description": "กัวเตมาลา" },
        { "code": "GU", "value": "GUAM", "description": "กวม" },
        { "code": "GW", "value": "GUINEA-BISSAU", "description": "กินีบิสเซา" },
        { "code": "GY", "value": "GUYANA", "description": "กายอานา" },
        { "code": "HK", "value": "HONG KONG", "description": "ฮ่องกง" },
        { "code": "HM", "value": "HEARD AND MCDONALD ISLANDS", "description": "เกาะเฮิร์ดและหมู่เกาะแมกดอนัลด์" },
        { "code": "HN", "value": "HONDURAS", "description": "ฮอนดูรัส" },
        { "code": "HR", "value": "CROATIA", "description": "โครเอเชีย" },
        { "code": "HT", "value": "HAITI", "description": "เฮติ" },
        { "code": "HU", "value": "HUNGARY", "description": "ฮังการี" },
        { "code": "ID", "value": "INDONESIA", "description": "อินโดนีเซีย" },
        { "code": "IE", "value": "IRELAND", "description": "ไอร์แลนด์" },
        { "code": "IL", "value": "ISRAEL", "description": "อิสราเอล" },
        { "code": "IM", "value": "ISLE OF MAN", "description": "เกาะแมน" },
        { "code": "IN", "value": "INDIA", "description": "อินเดีย" },
        { "code": "IO", "value": "BRITISH INDIAN OCEAN TERRITORY", "description": "บริติชอินเดียนโอเชียนเทร์ริทอรี" },
        { "code": "IQ", "value": "IRAQ", "description": "อิรัก" },
        { "code": "IR", "value": "IRAN (ISLAMIC REPUBLIC OF)", "description": "อิหร่าน" },
        { "code": "IS", "value": "ICELAND", "description": "ไอซ์แลนด์" },
        { "code": "IT", "value": "ITALY", "description": "อิตาลี" },
        { "code": "JE", "value": "JERSEY, C.I.", "description": "เจอซี่" },
        { "code": "JM", "value": "JAMAICA", "description": "จาเมกา" },
        { "code": "JO", "value": "JORDAN", "description": "จอร์แดน" },
        { "code": "JP", "value": "JAPAN", "description": "ญี่ปุ่น" },
        { "code": "KE", "value": "KENYA", "description": "เคนยา" },
        { "code": "KG", "value": "KYRGYZSTAN", "description": "คีร์กีซสถาน" },
        { "code": "KH", "value": "CAMBODIA", "description": "กัมพูชา" },
        { "code": "KI", "value": "KIRIBATI", "description": "คิริบาส, คิริบาตี" },
        { "code": "KM", "value": "COMOROS", "description": "คอโมโรส" },
        { "code": "KN", "value": "SAINT KITTS AND NEVIS", "description": "เซนต์คิตส์และเนวิส" },
        { "code": "KP", "value": "KOREA, DEMOCRATIC PEOPLE’S REPUBLIC OF", "description": "เกาหลีเหนือ" },
        { "code": "KR", "value": "KOREA, REPUBLIC OF", "description": "เกาหลีใต้" },
        { "code": "KW", "value": "KUWAIT", "description": "คูเวต" },
        { "code": "KY", "value": "CAYMAN ISLANDS", "description": "หมู่เกาะเคย์แมน" },
        { "code": "KZ", "value": "KAZAKHSTAN", "description": "คาซัคสถาน" },
        { "code": "LA", "value": "LAO PEOPLE’S DEMOCRATIC REPUBLIC", "description": "ลาว" },
        { "code": "LB", "value": "LEBANON", "description": "เลบานอน" },
        { "code": "LC", "value": "SAINT LUCIA", "description": "เซนต์ลูเซีย" },
        { "code": "LI", "value": "LIECHTENSTEIN", "description": "ลิกเตนสไตน์" },
        { "code": "LK", "value": "SRI LANKA", "description": "ศรีลังกา" },
        { "code": "LR", "value": "LIBERIA", "description": "ไลบีเรีย" },
        { "code": "LS", "value": "LESOTHO", "description": "เลโซโท" },
        { "code": "LT", "value": "LITHUANIA", "description": "ลิทัวเนีย" },
        { "code": "LU", "value": "LUXEMBOURG", "description": "ลักเซมเบิร์ก" },
        { "code": "LV", "value": "LATVIA", "description": "ลัตเวีย" },
        { "code": "LY", "value": "LIBYAN ARAB JAMAHIRIYA", "description": "ลิเบีย" },
        { "code": "MA", "value": "MOROCCO", "description": "โมร็อกโก" },
        { "code": "MC", "value": "MONACO", "description": "โมนาโก" },
        { "code": "MD", "value": "MOLDOVA, REPUBLIC OF", "description": "มอลโดวา" },
        { "code": "ME", "value": "MONTENEGRO", "description": "มอนเตเนโกร" },
        { "code": "MF", "value": "SAINT-MARTIN", "description": "เซนต์มาร์ติน" },
        { "code": "MG", "value": "MADAGASCAR", "description": "มาดากัสการ์" },
        { "code": "MH", "value": "MARSHALL ISLANDS", "description": "หมู่เกาะมาร์แชลล์" },
        { "code": "MK", "value": "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF", "description": "มาซิโดเนีย" },
        { "code": "ML", "value": "MALI", "description": "มาลี" },
        { "code": "MM", "value": "MYANMAR", "description": "พม่า" },
        { "code": "MN", "value": "MONGOLIA", "description": "มองโกเลีย" },
        { "code": "MO", "value": "MACAO", "description": "มาเก๊า" },
        { "code": "MP", "value": "NORTHERN MARIANA ISLANDS", "description": "หมู่เกาะนอร์เทิร์นมาเรียนา" },
        { "code": "MQ", "value": "MARTINIQUE", "description": "มาร์ตินีก" },
        { "code": "MR", "value": "MAURITANIA", "description": "มอริเตเนีย" },
        { "code": "MS", "value": "MONTSERRAT", "description": "มอนต์เซอร์รัต" },
        { "code": "MT", "value": "MALTA", "description": "มอลตา" },
        { "code": "MU", "value": "MAURITIUS", "description": "มอริเชียส" },
        { "code": "MV", "value": "MALDIVES", "description": "มัลดีฟส์" },
        { "code": "MW", "value": "MALAWI", "description": "มาลาวี" },
        { "code": "MX", "value": "MEXICO", "description": "เม็กซิโก" },
        { "code": "MY", "value": "MALAYSIA", "description": "มาเลเซีย" },
        { "code": "MZ", "value": "MOZAMBIQUE", "description": "โมซัมบิก" },
        { "code": "NA", "value": "NAMIBIA", "description": "นามิเบีย" },
        { "code": "NC", "value": "NEW CALEDONIA", "description": "นิวแคลิโดเนีย, นูแวลกาเลโดนี" },
        { "code": "NE", "value": "NIGER", "description": "ไนเจอร์" },
        { "code": "NF", "value": "NORFOLK ISLAND", "description": "เกาะนอร์ฟอล์ก" },
        { "code": "NG", "value": "NIGERIA", "description": "ไนจีเรีย" },
        { "code": "NI", "value": "NICARAGUA", "description": "นิการากัว" },
        { "code": "NL", "value": "NETHERLANDS", "description": "เนเธอร์แลนด์" },
        { "code": "NO", "value": "NORWAY", "description": "นอร์เวย์" },
        { "code": "NP", "value": "NEPAL", "description": "เนปาล" },
        { "code": "NR", "value": "NAURU", "description": "นาอูรู" },
        { "code": "NU", "value": "NIUE", "description": "นีอูเอ" },
        { "code": "NZ", "value": "NEW ZEALAND", "description": "นิวซีแลนด์" },
        { "code": "OM", "value": "OMAN", "description": "โอมาน" },
        { "code": "PA", "value": "PANAMA", "description": "ปานามา" },
        { "code": "PE", "value": "PERU", "description": "เปรู" },
        { "code": "PF", "value": "FRENCH POLYNESIA", "description": "เฟรนช์โปลินีเซีย" },
        { "code": "PG", "value": "PAPUA NEW GUINEA", "description": "ปาปัวนิวกินี" },
        { "code": "PH", "value": "PHILIPPINES", "description": "ฟิลิปปินส์" },
        { "code": "PK", "value": "PAKISTAN", "description": "ปากีสถาน" },
        { "code": "PL", "value": "POLAND", "description": "โปแลนด์" },
        { "code": "PM", "value": "SAINT PIERRE AND MIQUELON", "description": "แซงปิแยร์และมีเกอลง" },
        { "code": "PN", "value": "PITCAIRN", "description": "หมู่เกาะพิตแคร์น" },
        { "code": "PR", "value": "PUERTO RICO", "description": "เครือรัฐเปอร์โตริโก" },
        { "code": "PS", "value": "PALESTINE, STATE OF", "description": "ปาเลสไตน์" },
        { "code": "PT", "value": "PORTUGAL", "description": "โปรตุเกส" },
        { "code": "PW", "value": "PALAU", "description": "ปาเลา" },
        { "code": "PY", "value": "PARAGUAY", "description": "ปารากวัย" },
        { "code": "PZ", "value": "PANAMA CANAL ZONE", "description": "คลองปานามา" },
        { "code": "QA", "value": "QATAR", "description": "กาตาร์" },
        { "code": "RE", "value": "REUNION", "description": "เรอูนียง" },
        { "code": "RO", "value": "ROMANIA", "description": "โรมาเนีย" },
        { "code": "RS", "value": "SERBIA", "description": "เซอร์เบีย" },
        { "code": "RU", "value": "RUSSIAN FEDERATION", "description": "รัสเซีย" },
        { "code": "RW", "value": "RWANDA", "description": "รวันดา" },
        { "code": "SA", "value": "SAUDI ARABIA", "description": "ซาอุดีอาระเบีย" },
        { "code": "SB", "value": "SOLOMON ISLANDS", "description": "หมู่เกาะโซโลมอน" },
        { "code": "SC", "value": "SEYCHELLES", "description": "เซเชลส์" },
        { "code": "SD", "value": "SUDAN", "description": "ซูดาน" },
        { "code": "SE", "value": "SWEDEN", "description": "สวีเดน" },
        { "code": "SG", "value": "SINGAPORE", "description": "สิงคโปร์" },
        { "code": "SH", "value": "SAINT HELENA", "description": "เซนต์เฮเลนา" },
        { "code": "SI", "value": "SLOVENIA", "description": "สโลวีเนีย" },
        { "code": "SJ", "value": "SVALBARD AND JAN MAYEN ISLANDS", "description": "สฟาลบาร์" },
        { "code": "SK", "value": "SLOVAKIA", "description": "สโลวาเกีย" },
        { "code": "SL", "value": "SIERRA LEONE", "description": "เซียร์ราลีโอน" },
        { "code": "SM", "value": "SAN MARINO", "description": "ซานมารีโน" },
        { "code": "SN", "value": "SENEGAL", "description": "เซเนกัล" },
        { "code": "SO", "value": "SOMALIA", "description": "โซมาเลีย" },
        { "code": "SR", "value": "SURINAME", "description": "ซูรินาเม" },
        { "code": "ST", "value": "SAO TOME AND PRINCIPE", "description": "เซาตูเมและปรินซิปี" },
        { "code": "SV", "value": "EL SALVADOR", "description": "เอลซัลวาดอร์" },
        { "code": "SY", "value": "SYRIAN ARAB REPUBLIC", "description": "ซีเรีย" },
        { "code": "SZ", "value": "ESWATINI", "description": "เอสวาตีนี" },
        { "code": "TC", "value": "TURKS AND CAICOS ISLANDS", "description": "หมู่เกาะเติกส์และหมู่เกาะเคคอส" },
        { "code": "TD", "value": "CHAD", "description": "ชาด" },
        { "code": "TF", "value": "FRENCH SOUTHERN TERRITORIES", "description": "เฟรนช์เซาเทิร์นและแอนตาร์กติกเทร์ริทอรีส์" },
        { "code": "TG", "value": "TOGO", "description": "โตโก" },
        { "code": "TH", "value": "THAILAND", "description": "ไทย" },
        { "code": "TJ", "value": "TAJIKISTAN", "description": "ทาจิกิสถาน" },
        { "code": "TK", "value": "TOKELAU", "description": "โตเกเลา" },
        { "code": "TL", "value": "EAST TIMOR", "description": "ติมอร์-เลสเต" },
        { "code": "TM", "value": "TURKMENISTAN", "description": "เติร์กเมนิสถาน" },
        { "code": "TN", "value": "TUNISIA", "description": "ตูนิเซีย" },
        { "code": "TO", "value": "TONGA", "description": "ตองกา" },
        { "code": "TP", "value": "EAST TIMOR", "description": "ติมอร์ตะวันออก" },
        { "code": "TR", "value": "TURKEY", "description": "ตุรกี" },
        { "code": "TT", "value": "TRINIDAD AND TOBAGO", "description": "ตรินิแดดและโตเบโก" },
        { "code": "TV", "value": "TUVALU", "description": "ตูวาลู" },
        { "code": "TW", "value": "TAIWAN, PROVINCE OF CHINA", "description": "ไต้หวัน" },
        { "code": "TZ", "value": "TANZANIA, UNITED REPUBLIC OF", "description": "แทนซาเนีย" },
        { "code": "UA", "value": "UKRAINE", "description": "ยูเครน" },
        { "code": "UG", "value": "UGANDA", "description": "ยูกันดา" },
        { "code": "UM", "value": "UNITED STATES MINOR OUTLYING ISLANDS", "description": "ยูเอส ไมเนอร์" },
        { "code": "US", "value": "UNITED STATES", "description": "สหรัฐอเมริกา" },
        { "code": "UY", "value": "URUGUAY", "description": "อุรุกวัย" },
        { "code": "UZ", "value": "UZBEKISTAN", "description": "อุซเบกิสถาน" },
        { "code": "VA", "value": "HOLY SEE (VATICAN CITY STATE)", "description": "นครรัฐวาติกัน" },
        { "code": "VC", "value": "SAINT VINCENT AND THE GRENADINES", "description": "เซนต์วินเซนต์ และเกรนาดีนส์" },
        { "code": "VE", "value": "VENEZUELA, BOLIVARIAN REPUBLIC OF", "description": "เวเนซุเอลา" },
        { "code": "VG", "value": "VIRGIN ISLANDS (BRITISH)", "description": "หมู่เกาะเวอร์จินของอังกฤษ" },
        { "code": "VI", "value": "VIRGIN ISLANDS (U.S.)", "description": "หมู่เกาะเวอร์จินของสหรัฐอเมริกา" },
        { "code": "VN", "value": "VIET NAM", "description": "เวียดนาม" },
        { "code": "VU", "value": "VANUATU", "description": "วานูอาตู" },
        { "code": "WF", "value": "WALLIS AND FUTUNA ISLANDS", "description": "หมู่เกาะวาลลิสและหมู่เกาะฟุตูนา" },
        { "code": "WS", "value": "SAMOA", "description": "ซามัว" },
        { "code": "YE", "value": "YEMEN", "description": "เยเมน" },
        { "code": "YT", "value": "MAYOTTE", "description": "มายอต" },
        { "code": "YU", "value": "YUGOSLAVIA", "description": "ยูโกสลาเวีย" },
        { "code": "ZA", "value": "SOUTH AFRICA", "description": "แอฟริกาใต้" },
        { "code": "ZM", "value": "ZAMBIA", "description": "แซมเบีย" },
        { "code": "ZW", "value": "ZIMBABWE", "description": "ซิมบับเว" },
        { "code": "BQ", "value": "BONAIRE, SAINT EUSTATIUS AND SABA", "description": "โบแนร์ ซินท์เอิสทาทิอุส และ ซาบา" },
        { "code": "CW", "value": "CURACAO", "description": "คูราเซา" },
        { "code": "SS", "value": "SOUTH SUDAN", "description": "เซาท์ซูดาน" },
        { "code": "SX", "value": "SINT MAARTEN (DUTCH PART)", "description": "ซินท์มาร์เทิน" },
        { "code": "99", "value": "ไม่ระบุ", "description": "Unclassified" },
    ]
    for country in countries:
        if country["value"] == input_value or country["description"] == input_value:
            return country["code"]
    return None